#!/usr/bin/env bash
# Regenerate assets/cdn_ranges.txt from upstream CDN feeds.
#
# Runnable locally to refresh the bundled snapshot. Failures on individual
# feeds are fatal — we'd rather skip the refresh than ship a partial file.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/assets/cdn_ranges.txt"

require() {
    command -v "$1" >/dev/null 2>&1 || {
        echo "error: missing required tool: $1" >&2
        exit 1
    }
}

require curl
require jq

fetch_cloudflare_v4() {
    curl -fsS https://www.cloudflare.com/ips-v4 \
        | grep -E '^[0-9.]+/[0-9]+$' \
        | sed 's/^/cloudflare /'
}

fetch_cloudflare_v6() {
    curl -fsS https://www.cloudflare.com/ips-v6 \
        | grep -E '^[0-9a-fA-F:]+/[0-9]+$' \
        | sed 's/^/cloudflare /'
}

fetch_fastly_v4() {
    curl -fsS https://api.fastly.com/public-ip-list \
        | jq -r '.addresses[]' \
        | sed 's/^/fastly /'
}

fetch_fastly_v6() {
    curl -fsS https://api.fastly.com/public-ip-list \
        | jq -r '.ipv6_addresses[]' \
        | sed 's/^/fastly /'
}

# GitHub Pages doesn't expose a machine-readable feed; the published ranges
# are stable enough to hardcode and update by hand on the rare occasion they
# change.
github_pages_ranges() {
    cat << 'EOF'
github_pages 185.199.108.0/22
github_pages 2606:50c0::/32
EOF
}

{
    cat << 'EOF'
# CDN IP ranges bundled at build time.
# Format: `<provider> <CIDR>`. Blank lines and `#` comments allowed.
#
# Generated by scripts/refresh-cdn-ranges.sh. To add a provider, edit that
# script and regenerate this file.
#
# Sources (snapshot — refresh via the script):
#   - Cloudflare: https://www.cloudflare.com/ips-v4 / ips-v6
#   - Fastly:     https://api.fastly.com/public-ip-list
#   - GitHub Pages: documented at docs.github.com/pages

# --- Cloudflare IPv4 ---
EOF
    fetch_cloudflare_v4
    echo
    echo "# --- Cloudflare IPv6 ---"
    fetch_cloudflare_v6
    echo
    echo "# --- Fastly IPv4 ---"
    fetch_fastly_v4
    echo
    echo "# --- Fastly IPv6 ---"
    fetch_fastly_v6
    echo
    echo "# --- GitHub Pages ---"
    github_pages_ranges
} > "$OUT.tmp"

mv "$OUT.tmp" "$OUT"
echo "Wrote $OUT"
